# Generated by Django 3.1.7 on 2021-02-26 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Individual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gedcom_id', models.CharField(blank=True, max_length=200)),
                ('name_last', models.CharField(default='НЕИЗВЕСТНО', max_length=200)),
                ('name_first', models.CharField(blank=True, max_length=200)),
                ('patronym', models.CharField(blank=True, max_length=200)),
                ('name_maiden', models.CharField(blank=True, max_length=200)),
                ('gender', models.CharField(blank=True, choices=[('F', 'женский'), ('M', 'мужской'), ('U', 'неизвестно')], max_length=3)),
                ('date_birth', models.CharField(blank=True, max_length=200)),
                ('date_death', models.CharField(blank=True, max_length=200)),
                ('place_birth', models.CharField(blank=True, max_length=200)),
                ('place_death', models.CharField(blank=True, max_length=200)),
                ('individual_notes', models.TextField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_type', models.CharField(blank=True, max_length=200)),
                ('individual_1_role', models.CharField(blank=True, max_length=200)),
                ('individual_2_role', models.CharField(blank=True, max_length=200)),
                ('marriage_date', models.CharField(blank=True, max_length=200)),
                ('individual_1_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Individual_1', to='familyroster.individual')),
                ('individual_2_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Individual_2', to='familyroster.individual')),
            ],
        ),
    ]
